spring.application.name=order-service
server.port=8903

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/app_db}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=AWS_MSK_IAM
spring.kafka.properties.sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required;
spring.kafka.properties.sasl.client.callback.handler.class=software.amazon.msk.auth.iam.IAMClientCallbackHandler
spring.kafka.admin.auto-create=true
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
management.tracing.enabled=${MANAGEMENT_TRACING_ENABLED:false}
management.zipkin.tracing.enabled=${MANAGEMENT_ZIPKIN_TRACING_ENABLED:false}

spring.cloud.openfeign.client.config.stock-service.connectTimeout=1000
spring.cloud.openfeign.client.config.stock-service.readTimeout=1000

resilience4j.circuitbreaker.instances.stockService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.stockService.sliding-window-size=3
resilience4j.circuitbreaker.instances.stockService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.stockService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.stockService.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.stockService.permitted-number-of-calls-in-half-open-state=1
resilience4j.circuitbreaker.instances.stockService.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.retry.instances.stockService.max-attempts=1
resilience4j.retry.instances.stockService.wait-duration=0ms

logging.level.io.github.resilience4j.circuitbreaker=DEBUG
