spring.application.name=product-service
server.port=8901

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/app_db}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect